initial attempt to setup testing running lbann with prototext files through model->setup(). The script iteratively searches for runme.py files, then constructs and prints an srun line, e.g:
srun --nodes=1 --ntasks-per-node=12 ../../../build/catalyst.llnl.gov/model_zoo/lbann --exit_after_setup --model=/usr/workspace/wsb/hysom/TEST11/lbann/model_zoo/models/python/../autoencoder_mnist/model_autoencoder_mnist.prototext --reader=/usr/workspace/wsb/hysom/TEST11/lbann/model_zoo/models/python/../autoencoder_mnist/../../data_readers/data_reader_mnist.prototext --optimizer=../../optimizers/opt_adam.prototext

The --exit_after_setup causes model_zoo/lbann to exit after the call to model->setup()

There are currently six runme.py files; status of each:

PASSES: autoencoder_cifar10, autoencoder_mnist, resnet50
ERROR:  alexnet, greedy_layerwise_autoencoder_mnist, imagenet

ERRORS:

  alexnet  - LBANN: rank 0 of model 0 caught error message:  imcomm: trying to do inter-model gradient communication on layer 2 without gradients

  greedy_layerwise_autoencoder_mnist - LBANN: rank 0 of model 0 caught error message:  Layer: too many child layers

  imagenet - hangs after: adding print callback with interval: 1
    0:[ input:partitioned] Set up a layer with input       0 and  196608 neurons. (3 x 256 x 256)

Am now trying to figure out if the ERRORS were caused by my recent pushes, or if they were
previously broken.